- name: Check version of hitachivantara.vspone_block
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  tasks:
    - name: "Set My Pool to use"
      set_fact:
        version_hitachi: "{{ lookup('vspone_block', 'hitachivantara') }}"
    - debug: var=version_hitachi

