####################################################################
# Create PVOL Host Group
####################################################################
- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ansible_vault_gateway_var.yml
    - ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml
  tasks:
    - name: Create hostgroup
      hv_hg:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ gateway_token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          name: "{{ hostgroup_name_1 }}"
          port: "{{ hostgroup_port_1 }}"
          host_mode: "{{ hostgroup_host_mode_1 }}"
          host_mode_options: "{{ hostgroup_host_mode_options_1 }}"
          ldevs:  [ "{{ created_ldev_id }}" ]
          wwns: "{{ hostgroup_wwns_1 }}"
      register: result
    - debug:
        var: result
