####################################################################
# Create LDEV
####################################################################
- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars:
    - ldev_pool_id_1: "{{pool_id}}"
    - ldev_size_1: "{{size_1}}"
    - ldev_name_1: "{{name_1}}"
  tasks:
    - name: Create Ldev
      hv_ldev:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ gateway_token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          pool_id: "{{ ldev_pool_id_1 }}"
          size: "{{ ldev_size_1 }}"
          name: "{{ ldev_name_1 }}"
      register: result
    - name: Set LDEV ID
      set_stats:
        data:
           created_ldev_id: "{{ result.data.ldev_id }}"
    - debug: var=created_ldev_id
        
