####################################################################
# Create HUR PAIR
####################################################################
- name: Create HUR PAIR Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars_files:
    - ansible_vault_gateway_var.yml
    - ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml
  tasks:
    - name: Create HUR pair
      hv_hur:
        storage_system_info:
          serial: '{{ storage_serial }}'
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ gateway_token }}"
        spec:
          primary_volume_id: "{{ created_ldev_id }}"
          primary_volume_journal_id: "{{ hur_primary_volume_journal_id_1 }}"
          secondary_volume_journal_id: "{{ hur_secondary_volume_journal_id_1 }}"
          secondary_pool_id: "{{ hur_secondary_pool_id_1 }}"
          allocate_new_consistency_group: "{{ hur_allocate_new_consistency_group_1 }}"
          secondary_storage_serial_number: "{{ storage_serial_2 }}"
          secondary_hostgroup:  "{{ hur_secondary_hostgroup_1 }}"
      register: result
    - debug:
        var: result
