####################################################################
# Create PVOL Host Group
####################################################################
- name: Hostgroup Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars:
    - hostgroup_name_1: "{{name_1}}"
    - hostgroup_port_1: "{{port_1}}"
    - hostgroup_host_mode_1: "{{host_mode_1}}"
    - hostgroup_host_mode_options_1: "{{host_mode_options_1}}"
    - wwns: "{{hostgroup_wwns_1}}"
  tasks:
    - name: Create hostgroup
      hv_hg:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ gateway_token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          name: "{{ hostgroup_name_1 }}"
          port: "{{ hostgroup_port_1 }}"
          host_mode: "{{ hostgroup_host_mode_1 }}"
          host_mode_options: "{{ hostgroup_host_mode_options_1 }}"
          ldevs:  [ "{{ created_ldev_id }}" ]
          wwns: "{{ hostgroup_wwns_1 }}"
      register: result
    - debug:
        var: result
