- name: Get Constants
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars:
    - data:
       v1: "{{gtwy_addr}}"
       v2: "{{gtwy_user}}"
       v3: "{{gtwy_pass}}"
       v4: "gateway"
       v5: "{{pvol_serial}}"
       v6: "{{pvol_ip}}"
       v7: "{{storage_user}}"
       v8: "{{storage_pass}}"
       v9: "{{svol_serial}}"
       v10: "{{svol_ip}}"
       v11: "present"
  tasks:
    - debug:  var:data
