- name: Get Constants
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp
  vars:
    - uai_gateway_address: "{{gtwy_addr}}"
    - vault_gateway_username: "{{gtwy_user}}"
    - vault_gateway_secret: "{{gtwy_pass}}"
    - connection_type: "gateway"
    - storage_serial: "{{pvol_serial}}"
    - storage_address: "{{pvol_ip}}"
    - vault_storage_username: "{{storage_user}}"
    - vault_storage_secret: "{{storage_pass}}"
    - storage_serial_2: "{{svol_serial}}"
    - storage_address_2: "{{svol_ip}}"
    - state_present: "present"
  tasks:
    - debug:
        msg:
          m1: "{{ uai_gateway_address }}"
          m2: "{{ vault_gateway_username }}"
          m3: "{{ connection_type }}"
     
