####################################################################
# Get Gateway Token
####################################################################
- name: Gateway Token  Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ansible_vault_gateway_var.yml
    - ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml
  tasks:
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False
    - name: Set gateway token
      set_stats:
        data:
           gateway_token: "{{ result_token.api_token.token }}"
    - debug:
        var: gateway_token
